### ISSUE TITLE
unable to build on ubuntu14.04

### ISSUE THREAD

**Issue by winkar** [abeluck/stegdetect#2]
while making 
"make[2]: **\* No rule to make target `Magdir/varied.out', needed by`magic'.  Stop."
what happened?

**Comment by SirGerbs** [comment]
@fyth Thanks a lot!! I've been trying to get stegdetect to work for days without success due to dependency issues and whatnot. Your suggestion worked and stegdetect is now installed. However, now I have an issue with stegbreak, saying that /usr/share/stegbreak/rules.ini doesn't exist. Did you run into the same issue? I downloaded a rules.ini file ( from the bottom of this thread https://bugs.launchpad.net/ubuntu/+source/stegdetect/+bug/55363) but now I get a segmentation fault. Any suggestions?

**Comment by fyth** [comment]
@SirGerbs Sorry pal, Haven't seen that before.   :(
If u do work it out somehow, pls leave a comment here.
Goodluck.  :)

**Comment by eugenekolo** [comment]
This works:
```
git clone https://github.com/abeluck/stegdetect
cd stegdetect
wget -O file/Magdir/varied.out https://raw.githubusercontent.com/file/file/master/magic/Magdir/varied.out
linux32 ./configure
linux32 make
```

**Comment by xingtian666** [comment]
@eugenekolo 
THX,It is very useful !!!

**Comment by felipe-dachshund** [comment]
@abeluck This issue happens 'cause the line
```
*.out
```
(line 16) appears in `.gitignore`. An exception must be put there for `file/Magdir/varied.out`.

**Comment by Peterpan0927** [comment]
that's quite simple, you can just make a file named varied.out in the path stegdetect-master/file/Magdir,and then use the command `linux32 make` ,everything will be ok

**Comment by abeluck** [comment]
Thanks to @redNixon the build is working again.
